spring:
  application:
    name: Journaler API

  datasource:
    url: jdbc:mysql://localhost:3306/journaler_api
    username: root
    password: docker
    initialization-mode: always
    tomcat:
      test-on-borrow: true
      validation-interval: 30000
      validation-query: SELECT 1
      remove-abandoned: true
      remove-abandoned-timeout: 10000
      log-abandoned: true
      max-age: 1800000
      log-validation-errors: true
      max-active: 50
      max-idle: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  output:
    ansi:
      enabled: always

endpoints:
  health:
    enabled: true
  trace:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true

server:
  port: 8080



